// List quizzes

/*
* Quiz Name
* No of Questions
* No of Responses
* Time Generated
* */

import Link from 'next/link'
import React from 'react'

const Page = ({params: {classroomId}}: {params: {classroomId: string}}) => {
  return (
    <div className=' flex flex-col gap-2'>
    <div className="flex justify-between items-end border-b pb-2">
				<nav className="font-medium p-2 flex gap-[1.875rem] max-sm:gap-3 max-sm:text-sm">
					<Link href={`/teacher/classrooms/${classroomId}/lectures`}
					      className="">Lectures</Link>
					<Link href={`/teacher/classrooms/${classroomId}/quiz`} className="relative text-black | after:content-[''] after:absolute after:-bottom-4 after:left-0 after:w-full after:h-1 after:rounded-full after:bg-[#0A349E]">
						Quizzes
					</Link>
					<Link href={`/teacher/classrooms/${classroomId}/notes`} className="">Notes</Link>
				</nav>
				{/* <button
					className="hidden | md:block py-[0.625rem] px-5 rounded-full border border-[#CBCBCB]" onClick={()=>setCreate(true)}
				>
					+ Create
				</button> */}
			</div>
	<div>
    <h1 className='text-4xl text-black font-medium'>Quizzes</h1>
    <p className='text-xl mt-4'>Questions generated by our model</p>
    <div className='quizCardWrapper | mt-3 grid gap-10 grid-cols-[repeat(auto-fill,minmax(350px,1fr))]'>
      <div className='quizCard | rounded-[0.625rem] border border-[#A0A0A0] text-center px-6 py-7'>
        <h1 className='text-xl text-black'>What is the Capital of Universe?</h1>
        <p className='mt-3'>Tap to reveal answers</p>
        <div className='mt-3 flex gap-3 flex-wrap justify-center'>
          <p className='text-sm text-[#0039C6] border border-[#5462DF] bg-[#CCE0FF] font-medium py-[0.375rem] px-3 rounded-full'>Questions: 12</p>
          <p className='text-sm text-[#00802B] border border-[#00B833] bg-[#CCFFE0] font-medium py-[0.375rem] px-3 rounded-full'>Responses: 12</p>
        </div>
      </div>
    </div>
	</div>
    </div>
  )
}

export default Page
