"use client"

/*
* Quiz Name
* No of Questions
* No of Responses
* Time Generated
* */

import NestedNav, { NavLink } from '@/components/NestedNav'
import useAuthStore from '@/lib/zustand'
import { getAllQuizzes } from '@/util/client/helpers'
import { Quiz } from '@prisma/client'
import Link from 'next/link'
import React, { useEffect, useState } from 'react'

const Page = ({params: {classroomId}}: {params: {classroomId: string}}) => {
	const {user} = useAuthStore()
	const [data, setData] = useState<Quiz[]>([]);

	useEffect(() => {
		const getData = async () => {
			if (!user) return;
			const quizzes = await getAllQuizzes(user.userOrgId, classroomId)
			if (quizzes) setData(quizzes)
		}
		getData()
	}, [user])

	const navlinks : NavLink[] = [
		{
			href: `/student/classrooms/${classroomId}/lectures`,
			title: "Lectures"
		},
		{
			href: `/student/classrooms/${classroomId}/quiz`,
			title: "Quizzes"
		},
		{
			href: `/student/classrooms/${classroomId}/notes`,
			title: "Notes"
		},
    {
        href: `/student/classrooms/${classroomId}/resources`,
  title: "Resources"
    }
	
	]
  return (
    <div className=' flex flex-col gap-2'>
			<NestedNav items={navlinks} button={(<></>)}/>
	<div>
    <h1 className='text-4xl text-black font-medium'>Quizzes</h1>
    <p className='text-xl mt-4'>Questions generated by our model</p>
    <div className='quizCardWrapper | mt-3 grid gap-10 grid-cols-[repeat(auto-fill,minmax(350px,1fr))]'>
      {data.map((item) => (<QuizCard item={item} key={item.quizId}/>))}
    </div>
	</div>
    </div>
  )
}

export default Page
